backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "img"
collections:
  - name: "image"
    label: "Image"
    folder: "/"
    create: true
    files: "img"

